language: php
php:
  - '5.6'
  - '5.5'
  - '5.4'
  - '5.3'

services:
  - mongodb

env:
  global:
    - TEST_PHP_ARGS="-q -s output.txt -g XFAIL,FAIL,BORK,WARN,LEAK,SKIP -x --show-diff"
    - REPORT_EXIT_STATUS=1
    - secure: uOPk40++5SqPwsvENvQXKy3sJmOYFoPxTSPpoafbus9teEqe3S0mXAv6leSUSH4K/vk1OoPFp2xjKRVkdBTeqTElna1DDWOuYlvli9PLSvyZ+b1bV+8Ap18BxqlYhd3tHrY7tIliOsh6dZplWF9GyUm9DWBZ/80uKUidh/Brg/Y=
    - secure: "pfGVPucvgcgcefhtzAVeejlpOtn4TnAqJSTM8mJkBl36KdU9P7hMuD3czQ4drWgzZ373/VT5UVhLu/HNsdbW0YBTeqPKJ4YNjqVVLytI8xT7y2Lw9l+I7o93j98TMgAoo8nVRmp/E4D6yutbKK1eddrcmf899R1iJbw8v8d1Ht8="

before_install:
  - sudo pip install cpp-coveralls
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb-org
  - sudo apt-get install gdb valgrind
  - sudo apt-get install cdbs debhelper build-essential python-lxml

before_script:
  - ulimit -a
  - ulimit -c unlimited || true
  - "./.travis.scripts/compile.sh"
  - make composer

notifications:
  email:
  - bjori@mongodb.com

script:
  - make test

after_success:
  - make coveralls

after_failure:
  - find . -name \*core\* -exec ./.travis.scripts/debug-core.sh {} \;

addons:
  coverity_scan:
    project:
      name: "bjori/phongo"
      description: "New generation MongoDB driver for PHP"
    notification_email: bjori@mongodb.com
    build_command_prepend: make clean
    build_command: make
    branch_pattern: coverity

