  - name: test-debian11-php-%phpVersion%
    tags: ["test", "debian", "x64", "php%phpVersion%", "pr", "tag"]
    display_name: "Test: Debian 11, PHP %phpVersion%"
    run_on: debian11-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian11"
      FETCH_BUILD_TASK: "build-php-%phpVersion%"
    depends_on:
      - variant: "build-debian11"
        name: "build-php-%phpVersion%"
    tasks:
      - ".standalone .local !.3.6 !.4.0 !.4.2 !.4.4 !.5.0"
      - ".replicaset .local !.3.6 !.4.0 !.4.2 !.4.4 !.5.0"
      - ".sharded .local !.3.6 !.4.0 !.4.2 !.4.4 !.5.0"
      - ".loadbalanced .local !.3.6 !.4.0 !.4.2 !.4.4 !.5.0"
      - "test-atlas-connectivity"
      - ".ocsp !.4.4 !.5.0"
    display_tasks:
      - name: "test-ocsp-latest"
        execution_tasks:
          - ".ocsp .latest"
      - name: "test-ocsp-rapid"
        execution_tasks:
          - ".ocsp .rapid"
      - name: "test-ocsp-7.0"
        execution_tasks:
          - ".ocsp .7.0"
      - name: "test-ocsp-6.0"
        execution_tasks:
          - ".ocsp .6.0"

  - name: test-debian92-php-%phpVersion%
    tags: ["test", "debian", "x64", "php%phpVersion%", "pr", "tag"]
    display_name: "Test: Debian 9.2, PHP %phpVersion%"
    run_on: debian92-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian92"
      FETCH_BUILD_TASK: "build-php-%phpVersion%"
    depends_on:
      - variant: "build-debian92"
        name: "build-php-%phpVersion%"
    tasks:
      # Remember to add new major versions here as they are released
      - ".standalone .local !.6.0 !.7.0 !.rapid !.latest"
      - ".replicaset .local !.6.0 !.7.0 !.rapid !.latest"
      - ".sharded .local !.6.0 !.7.0 !.rapid !.latest"
      - ".loadbalanced .local !.6.0 !.7.0 !.rapid !.latest"
      - ".ocsp !.6.0 !.7.0 !.rapid !.latest"
    display_tasks:
      - name: "test-ocsp-5.0"
        execution_tasks:
          - ".ocsp .5.0"
      - name: "test-ocsp-4.4"
        execution_tasks:
          - ".ocsp .4.4"
