name: "Release New Version"
run-name: "Release ${{ inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to be released. This is checked for consistency with the branch name and configuration"
        required: true
        type: "string"
      jira-version-number:
        description: "JIRA version ID (e.g. 54321)"
        required: true
        type: "string"

env:
  default-release-message: |
    The PHP team is happy to announce that version {0} of the [mongodb](https://pecl.php.net/package/mongodb) PHP extension is now available on PECL.

    **Release Highlights**

    TODO: one or more paragraphs describing important changes in this release

    A complete list of resolved issues in this release may be found in [JIRA](https://jira.mongodb.org/secure/ReleaseNote.jspa?version={1}&projectId=12484).

    **Documentation**

    Documentation is available on [PHP.net](https://php.net/set.mongodb).

    **Installation**

    You can either download and install the source manually, or you can install the extension with:

    ```
    pecl install mongodb-{0}
    ```

    or update with:

    ```
    pecl upgrade mongodb-{0}
    ```

    Windows binaries are attached to the GitHub release notes.

jobs:
  prepare-release:
    environment: release
    name: "Prepare release"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: "Create release output"
        run: echo 'ðŸŽ¬ Release process for version ${{ inputs.version }} started by @${{ github.triggering_actor }}' >> $GITHUB_STEP_SUMMARY

      - name: "Generate token and checkout repository"
        uses: mongodb-labs/drivers-github-tools/secure-checkout@v2
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          submodules: true

      - name: "Set up drivers-github-tools"
        uses: mongodb-labs/drivers-github-tools/setup@v2
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region_name: ${{ vars.AWS_REGION_NAME }}
          aws_secret_id: ${{ secrets.AWS_SECRET_ID }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Update version information to stable release"
        run: ./bin/update-release-version.php to-stable

      - name: "Read current package version"
        run: echo "PACKAGE_VERSION=$(./bin/update-release-version.php get-version)" >> "$GITHUB_ENV"

      # Sanity check - the version from the input and the one determined by phongo_version.h need to be the same
      - name: "Check version for consistency"
        if: ${{ inputs.version != env.PACKAGE_VERSION }}
        # We exit with an error to abort the workflow. This is only run if the versions don't match
        run: |
          echo 'âŒ Release failed due to version mismatch: expected ${{ inputs.version }}, got ${{ env.PACKAGE_VERSION }} from code' >> $GITHUB_STEP_SUMMARY
          exit 1

      #
      # Preliminary checks done - commence the release process
      #

      - name: "Create package commit"
        uses: mongodb-labs/drivers-github-tools/bump-version@v2
        with:
          version: ${{ inputs.version }}
          # Use get-version as a dummy as a version_bump_script is required
          # We run the bump script manually earlier so we can sanity-check the version number and print nice output
          version_bump_script: "./bin/update-release-version.php get-version"
          commit_template: 'Package ${VERSION}'
          # Don't push changes as we're creating a second commit later
          push_commit: false

      - name: "Create release tag"
        uses: mongodb-labs/drivers-github-tools/tag-version@v2
        with:
          version: ${{ inputs.version }}
          tag_message_template: 'Release ${VERSION}'

      - name: "Bump to next development release and commit"
        uses: mongodb-labs/drivers-github-tools/bump-version@v2
        with:
          version: ${{ inputs.version }}
          version_bump_script: "./bin/update-release-version.php to-next-patch-dev"
          commit_template: 'Back to -dev'

      # TODO: Manually merge using ours strategy. This avoids merge-up pull requests being created
      # Process is:
      # 1. switch to next branch (according to merge-up action)
      # 2. merge release branch using --strategy=ours
      # 3. push next branch
      # 4. switch back to release branch, then push

      - name: "Prepare release message"
        run: |
          cat > release-message <<'EOL'
          ${{ format(env.default-release-message, inputs.version, inputs.jira-version-number) }}
          EOL

      - name: "Create draft release"
        run: echo "RELEASE_URL=$(gh release create ${{ inputs.version }} --target ${{ github.ref_name }} --title "${{ inputs.version }}" --notes-file release-message --draft)" >> "$GITHUB_ENV"

      - name: "Set summary"
        run: |
          echo 'ðŸš€ Created tag and drafted release for version [${{ inputs.version }}](${{ env.RELEASE_URL }})' >> $GITHUB_STEP_SUMMARY
          echo 'âœï¸ You may now update the release notes and publish the release when ready' >> $GITHUB_STEP_SUMMARY

  static-analysis:
    needs: prepare-release
    name: "Run Static Analysis"
    uses: ./.github/workflows/static-analysis.yml
    with:
      ref: refs/tags/${{ inputs.version }}
    permissions:
      security-events: write
      id-token: write

  package-release:
    needs: prepare-release
    name: "Create Release Packages"
    uses: ./.github/workflows/package-release.yml
    with:
      version: ${{ inputs.version }}
      ref: refs/tags/${{ inputs.version }}
    secrets: inherit
    permissions:
      id-token: write
      contents: write

  publish-ssdlc-assets:
    needs:
      - static-analysis
      - package-release
    environment: release
    name: "Publish SSDLC Assets"
    runs-on: ubuntu-latest
    permissions:
      security-events: read
      id-token: write
      contents: write

    steps:
      - name: "Generate token and checkout repository"
        uses: mongodb-labs/drivers-github-tools/secure-checkout@v2
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          ref: refs/tags/${{ inputs.version }}

      # Sets the S3_ASSETS environment variable used later
      - name: "Set up drivers-github-tools"
        uses: mongodb-labs/drivers-github-tools/setup@v2
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region_name: ${{ vars.AWS_REGION_NAME }}
          aws_secret_id: ${{ secrets.AWS_SECRET_ID }}

      - name: Download all release artifacts
        run: gh release download ${{ inputs.version }} --dir ${{ env.RELEASE_ASSETS }}

      - name: "Generate authorized publication document"
        uses: mongodb-labs/drivers-github-tools/authorized-pub@v2
        with:
          product_name: "MongoDB PHP Driver (extension)"
          release_version: ${{ inputs.version }}
          filenames: "${{ env.RELEASE_ASSETS }}/*"
          token: ${{ env.GH_TOKEN }}

      - name: "Download SBOM file from Silk"
        uses: mongodb-labs/drivers-github-tools/sbom@v2
        with:
          silk_asset_group: mongodb-php-driver-extension

      - name: "Upload SBOM as release artifact"
        run: gh release upload ${{ inputs.version }} ${{ env.S3_ASSETS }}/cyclonedx.sbom.json
        continue-on-error: true

      - name: "Generate SARIF report from code scanning alerts"
        uses: mongodb-labs/drivers-github-tools/code-scanning-export@v2
        with:
          ref: ${{ inputs.version }}
          output-file: ${{ env.S3_ASSETS }}/code-scanning-alerts.json

      - name: "Generate compliance report"
        uses: mongodb-labs/drivers-github-tools/compliance-report@v2
        with:
          token: ${{ env.GH_TOKEN }}

      - name: Upload S3 assets
        uses: mongodb-labs/drivers-github-tools/upload-s3-assets@v2
        with:
          version: ${{ inputs.version }}
          product_name: mongo-php-driver
